site_name: Craftama Home Assistant apps
site_description: Home Assistant OS apps by Craftama
site_url: https://craftama.github.io/haos-apps/
repo_url: https://github.com/Craftama/haos-apps
repo_name: Craftama/haos-apps
edit_uri: edit/main/docs/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.edit

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Grafana Alloy: grafana_alloy.md
  - Home Assistant Exporter: home_assistant_exporter.md
  - Salt Minion: salt_minion.md
