---
name: "Home Assistant Exporter"
description: "Home Assistant metrics exporter for Prometheus"
version: "0.0.6"
slug: "home_assistant_exporter"
image: "ghcr.io/craftama/home_assistant_exporter/{arch}"
init: false
arch:
  - aarch64
  - amd64
homeassistant_api: true
host_network: true
ports:
  9878/tcp:
ports_description:
  9878/tcp: Exporter Web Port

options:
  hass_url: ""
  hass_token: ""
  log_level: "info"
schema:
  hass_url: str?
  hass_token: password?
  log_level: list(debug|info|warning|error|critical)
