---
name: "Grafana Alloy"
description: "OpenTelemetry Collector distribution with programmable pipelines"
version: "0.1.1"
slug: "grafana_alloy"
image: "ghcr.io/craftama/grafana_alloy/{arch}"
init: false
arch:
  - aarch64
  - amd64
ports:
  12345/tcp:
ports_description:
  12345/tcp: Alloy web server
journald: true
host_network: true
host_pid: true
docker_api: true

options:
  metrics_url: ""
  metrics_tenant: ""
  logs_url: ""
  logs_tenant: ""
  cluster_name: "HomeAssistant"
  env: ""
  region: ""
schema:
  metrics_url: str?
  metrics_tenant: str?
  logs_url: str?
  logs_tenant: str?
  cluster_name: str?
  env: str?
  region: str?
